---
- name: create prometheus user
  user:
    name: prometheus
    system: yes

- name: check prometheus
  stat:
    path: /opt/prometheus-{{ prometheus_version }}.linux-armv7/prometheus
  register: prometheus

- name: download promethus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-armv7.tar.gz
    dest: /opt
    remote_src: yes
    owner: prometheus
    group: prometheus
  when: not prometheus.stat.exists

- name: create data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: copy systemd file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0644
  notify:
    - restart prometheus

- name: copy rsyslog.d file
  copy:
    src: prometheus.conf.rsyslog.d
    dest: /etc/rsyslog.d/prometheus.conf
    mode: 0644
  notify:
    - restart rsyslog

- name: copy logrotate.d file
  copy:
    src: prometheus.logrotate.d
    dest: /etc/logrotate.d/prometheus
    mode: 0644

- name: copy prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
  notify:
    - restart prometheus

- name: start prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes